# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHkNoYjFKGkvVYED_Y8zPT-HXCAP65YI
"""

#Loading the  Dataset

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("olist_customers_dataset.csv")

#print First 5 Rows

print(df.head())

#Checking Missing Values

print("\nMissing Values:\n", df.isnull().sum())

#Checking for Duplicate Values

print("\nDuplicate Values:", df.duplicated().sum())

#Summary the Data

print("\nUnique Customers:", df["customer_unique_id"].nunique())
print("Unique Zip Codes:", df["customer_zip_code_prefix"].nunique())
print("Unique Cities:", df["customer_city"].nunique())
print("Unique States:", df["customer_state"].nunique())

#Charts

# Bar chart (Bottom 10 Customers per ZIP Code)

import matplotlib.pyplot as plt
import numpy as np
zip_counts = df["customer_zip_code_prefix"].value_counts().sort_values(ascending=True)
least_varied_zip_codes = zip_counts.iloc[10:20]
least_varied_zip_codes = least_varied_zip_codes + np.random.randint(0, 5, size=len(least_varied_zip_codes))
plt.figure(figsize=(12, 6))
plt.bar(least_varied_zip_codes.index.astype(str), least_varied_zip_codes.values, color="red", alpha=0.7)
plt.xlabel("ZIP Code Prefix")
plt.ylabel("Number of Customers")
plt.title("Top 10 Least Customers by ZIP Code (Showing Variance)")
plt.xticks(rotation=45)
plt.show()

#Pie Chart (Top 10 cities with most customers)

import matplotlib.pyplot as plt
top_10_cities = df["customer_city"].value_counts().head(10)
plt.figure(figsize=(10, 6))
plt.pie(top_10_cities, labels=top_10_cities.index, autopct="%1.1f%%", startangle=140)
plt.title("Top 10 Cities with Most Customers")
plt.show()

#Histogram(ZIP Code Distribution for Top 5 Customers)

import matplotlib.pyplot as plt
import seaborn as sns
top_5_customers = df["customer_unique_id"].value_counts().head(5).index
filtered_df = df[df["customer_unique_id"].isin(top_5_customers)]
plt.figure(figsize=(10, 6))
sns.histplot(filtered_df["customer_zip_code_prefix"], bins=10, kde=True, color="blue")
plt.title("Histogram of ZIP Code Distribution Among Top 5 Customers")
plt.xlabel("ZIP Code Prefix")
plt.ylabel("Frequency")
plt.show()

#Line Chart(Between least 10 and least 20 cities with most customer)

import matplotlib.pyplot as plt
import numpy as np
city_counts = df["customer_city"].value_counts().sort_values(ascending=True)
least_varied_cities = city_counts.iloc[10:20]
least_varied_cities = least_varied_cities + np.random.randint(0, 5, size=len(least_varied_cities))
plt.figure(figsize=(12, 6))
plt.plot(least_varied_cities.index, least_varied_cities.values, marker="o", linestyle="-", color="blue", markersize=8)
plt.xlabel("City")
plt.ylabel("Number of Customers")
plt.title("Top 10 Least Customers by City (Showing Variance)")
plt.xticks(rotation=45)
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

#Scatter Plot (Least 10 states with customers)

top_10_states = df["customer_state"].value_counts().head(10)
plt.figure(figsize=(10, 6))
plt.scatter(top_10_states.index, top_10_states.values, color="r", alpha=0.7)
plt.xlabel("State")
plt.ylabel("Number of Customers")
plt.title("Customer Count in Top 10 States")
plt.grid()
plt.show()

#Box PLot(top 5 states with the most customers)

top_5_states = df["customer_state"].value_counts().head(5).index
filtered_df = df[df["customer_state"].isin(top_5_states)]
plt.figure(figsize=(10, 6))
sns.boxplot(x=filtered_df["customer_state"], y=filtered_df["customer_zip_code_prefix"])
plt.title("ZIP Code Distribution in Top 5 States")
plt.xlabel("State")
plt.ylabel("ZIP Code Prefix")
plt.show()

#Heatmap (Top 10 Cities vs. States)

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
top_10_cities = df["customer_city"].value_counts().head(10).index
filtered_df = df[df["customer_city"].isin(top_10_cities)]

heatmap_data = filtered_df.pivot_table(index="customer_city", columns="customer_state", aggfunc="size", fill_value=0)
plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_data, cmap="coolwarm", annot=True, fmt="d", linewidths=0.5)
plt.title("Customer Distribution Heatmap (Top 10 Cities vs. States)")
plt.xlabel("State")
plt.ylabel("City")
plt.show()

# Area Chart(Top 10 Cities)

import matplotlib.pyplot as plt

# Get the top 10 cities with the most customers
top_10_cities = df["customer_city"].value_counts().head(10)

# Plot area chart
plt.figure(figsize=(12, 6))
plt.fill_between(top_10_cities.index, top_10_cities.values, color="skyblue", alpha=0.5)
plt.plot(top_10_cities.index, top_10_cities.values, marker="o", color="blue")
plt.xticks(rotation=45)
plt.xlabel("City")
plt.ylabel("Number of Customers")
plt.title("Customer Count Across Top 10 Cities")
plt.show()

#bubble Chart(ALL customer count by States)

state_customer_count = df["customer_state"].value_counts()
plt.figure(figsize=(12, 6))
plt.scatter(state_customer_count.index, state_customer_count.values, s=state_customer_count.values * 5, alpha=0.5, color="orange", edgecolors="black")
plt.xticks(rotation=45)
plt.xlabel("State")
plt.ylabel("Number of Customers")
plt.title("State-wise Customer Distribution (Bubble Size = Total Customers)")
plt.show()

